services:
  dev:
    build:
      context: .
      dockerfile: Containerfile.dev
  
    env_file:
      - .dev.env
    networks:
      - techtonic_plates_network
  host-mode:
    build:
      context: .
      dockerfile: Containerfile.dev
  
    env_file:
      - .dev.env
    networks_mode: "host"

  terraform:
    build:
      context: .
      dockerfile: container/Containerfile.terraform
    environment:
      - KAFKA_CONNECT_URL=http://kafka-connect:8083
    env_file:
      - .dev.env
    networks:
      - techtonic_plates_network
    depends_on:
      - dev
    volumes:
      - ./terraform:/terraform
    command: terraform plan

networks:
  techtonic_plates_network:
    external: true
