FROM docker.io/rust:latest

RUN cargo install cargo-watch
RUN cargo install sea-orm-cli@1.1.0
RUN rustup component add rustfmt

RUN apt update -y
RUN apt install -y make cmake libssl-dev libsasl2-dev libzstd-dev

# Install Terraform from HashiCorp repository
RUN wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com bookworm main" | tee /etc/apt/sources.list.d/hashicorp.list
RUN apt update && apt install terraform -y