//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::permission::Entity as Permission;
pub use super::user::Entity as User;
pub use super::user_permission::Entity as UserPermission;
