//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::permissions::Entity as Permissions;
pub use super::user_permissions::Entity as UserPermissions;
pub use super::users::Entity as Users;
